spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cat1bat2agu@gmail.com
    password: agucat1bat2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000